[2017-04-01 00:13:21.540] [INFO] console - Happy[1]: Version: 3.0.3. Using cache? yes. Threads: 3
[2017-04-01 00:13:21.599] [INFO] console - Happy[1]: Loaded 405 entries from cache. (0 were stale)
[2017-04-01 00:13:21.676] [INFO] console - Mongodb Connect Success!!!
[2017-04-01 00:13:21.737] [INFO] console - Happy[1]: All set; signalling webpack to proceed.
[2017-04-01 00:13:21.740] [INFO] console - webpack building...
[2017-04-01 00:13:34.185] [INFO] console - webpack built d4c8ba5a418a4356f5fd in 12621ms
[2017-04-01 00:13:48.337] [INFO] ::1 - GET /admin Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
[2017-04-01 00:14:53.168] [INFO] ::1 - GET /admin Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
[2017-04-01 07:31:32.937] [ERROR] console - Connection Error: Error: connection timeout
    at Db.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17)
    at emitTwo (events.js:106:13)
    at Db.emit (events.js:191:7)
    at Server.listener (/Users/creator/workspace/furuida/node_modules/mongodb/lib/db.js:1798:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb/lib/server.js:274:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/topologies/server.js:335:12)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/connection.js:185:10)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
[2017-04-01 08:23:25.868] [ERROR] console - Connection Error: Error: connection timeout
    at Db.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17)
    at emitTwo (events.js:106:13)
    at Db.emit (events.js:191:7)
    at Server.listener (/Users/creator/workspace/furuida/node_modules/mongodb/lib/db.js:1798:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb/lib/server.js:274:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/topologies/server.js:335:12)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/connection.js:185:10)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
[2017-04-01 08:23:56.171] [ERROR] console - Connection Error: { DisconnectedError: Ran out of retries trying to reconnect to "120.25.241.110:20000". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.
    at MongooseError.DisconnectedError (/Users/creator/workspace/furuida/node_modules/mongoose/lib/error/disconnected.js:21:11)
    at Server.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:64:31)
    at emitOne (events.js:101:20)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/topologies/server.js:317:16)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/pool.js:305:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  message: 'Ran out of retries trying to reconnect to "120.25.241.110:20000". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',
  name: 'DisconnectedError' }
[2017-04-01 16:27:59.765] [INFO] console - Happy[1]: Version: 3.0.3. Using cache? yes. Threads: 3
[2017-04-01 16:27:59.912] [INFO] console - Happy[1]: Loaded 405 entries from cache. (0 were stale)
[2017-04-01 16:28:00.084] [INFO] console - Happy[1]: All set; signalling webpack to proceed.
[2017-04-01 16:28:00.089] [INFO] console - webpack building...
[2017-04-01 16:28:03.091] [INFO] console - Mongodb Connect Success!!!
[2017-04-01 16:28:12.307] [INFO] console - webpack built d4c8ba5a418a4356f5fd in 12523ms
[2017-04-01 16:32:06.910] [ERROR] console - Connection Error: Error: connection timeout
    at Db.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17)
    at emitTwo (events.js:106:13)
    at Db.emit (events.js:191:7)
    at Server.listener (/Users/creator/workspace/furuida/node_modules/mongodb/lib/db.js:1798:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb/lib/server.js:274:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/topologies/server.js:335:12)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/connection.js:185:10)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
[2017-04-01 16:37:23.557] [ERROR] console - Connection Error: Error: connection timeout
    at Db.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17)
    at emitTwo (events.js:106:13)
    at Db.emit (events.js:191:7)
    at Server.listener (/Users/creator/workspace/furuida/node_modules/mongodb/lib/db.js:1798:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb/lib/server.js:274:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/topologies/server.js:335:12)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/connection.js:185:10)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
[2017-04-01 16:52:33.819] [ERROR] console - Connection Error: Error: connection timeout
    at Db.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17)
    at emitTwo (events.js:106:13)
    at Db.emit (events.js:191:7)
    at Server.listener (/Users/creator/workspace/furuida/node_modules/mongodb/lib/db.js:1798:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb/lib/server.js:274:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/topologies/server.js:335:12)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/connection.js:185:10)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
[2017-04-01 17:02:29.581] [ERROR] console - Connection Error: Error: connection timeout
    at Db.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17)
    at emitTwo (events.js:106:13)
    at Db.emit (events.js:191:7)
    at Server.listener (/Users/creator/workspace/furuida/node_modules/mongodb/lib/db.js:1798:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb/lib/server.js:274:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/topologies/server.js:335:12)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/connection.js:185:10)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
[2017-04-01 17:07:29.820] [ERROR] console - Connection Error: Error: connection timeout
    at Db.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17)
    at emitTwo (events.js:106:13)
    at Db.emit (events.js:191:7)
    at Server.listener (/Users/creator/workspace/furuida/node_modules/mongodb/lib/db.js:1798:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb/lib/server.js:274:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/topologies/server.js:335:12)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/connection.js:185:10)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
[2017-04-01 17:13:29.723] [ERROR] console - Connection Error: Error: connection timeout
    at Db.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17)
    at emitTwo (events.js:106:13)
    at Db.emit (events.js:191:7)
    at Server.listener (/Users/creator/workspace/furuida/node_modules/mongodb/lib/db.js:1798:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb/lib/server.js:274:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/topologies/server.js:335:12)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/connection.js:185:10)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
[2017-04-01 17:23:24.203] [ERROR] console - Connection Error: Error: connection timeout
    at Db.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17)
    at emitTwo (events.js:106:13)
    at Db.emit (events.js:191:7)
    at Server.listener (/Users/creator/workspace/furuida/node_modules/mongodb/lib/db.js:1798:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb/lib/server.js:274:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/topologies/server.js:335:12)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/connection.js:185:10)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
[2017-04-01 17:33:28.464] [ERROR] console - Connection Error: Error: connection timeout
    at Db.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17)
    at emitTwo (events.js:106:13)
    at Db.emit (events.js:191:7)
    at Server.listener (/Users/creator/workspace/furuida/node_modules/mongodb/lib/db.js:1798:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb/lib/server.js:274:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/topologies/server.js:335:12)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/connection.js:185:10)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
[2017-04-01 17:43:33.216] [ERROR] console - Connection Error: Error: connection timeout
    at Db.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17)
    at emitTwo (events.js:106:13)
    at Db.emit (events.js:191:7)
    at Server.listener (/Users/creator/workspace/furuida/node_modules/mongodb/lib/db.js:1798:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb/lib/server.js:274:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/topologies/server.js:335:12)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/connection.js:185:10)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
[2017-04-01 17:50:51.624] [ERROR] console - Connection Error: Error: connection timeout
    at Db.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17)
    at emitTwo (events.js:106:13)
    at Db.emit (events.js:191:7)
    at Server.listener (/Users/creator/workspace/furuida/node_modules/mongodb/lib/db.js:1798:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb/lib/server.js:274:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/topologies/server.js:335:12)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/connection.js:185:10)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
[2017-04-01 17:52:54.109] [ERROR] console - Connection Error: { DisconnectedError: Ran out of retries trying to reconnect to "120.25.241.110:20000". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.
    at MongooseError.DisconnectedError (/Users/creator/workspace/furuida/node_modules/mongoose/lib/error/disconnected.js:21:11)
    at Server.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:64:31)
    at emitOne (events.js:101:20)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/topologies/server.js:317:16)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/pool.js:305:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  message: 'Ran out of retries trying to reconnect to "120.25.241.110:20000". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',
  name: 'DisconnectedError' }
